//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRentalSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalEntities : DbContext
    {
        public MedicalEntities()
            : base("name=MedicalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alarma> Alarmas { get; set; }
        public virtual DbSet<Medic> Medics { get; set; }
        public virtual DbSet<Mesaje> Mesajes { get; set; }
        public virtual DbSet<Pacient> Pacients { get; set; }
        public virtual DbSet<Supraveghetor> Supraveghetors { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
