//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRentalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesaje
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> AuthorId { get; set; }
        public Nullable<System.Guid> ReciverId { get; set; }
        public string Mesaj { get; set; }
        public Nullable<int> AuthorType { get; set; }
    }
}
