//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRentalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacient
    {
        public System.Guid Id { get; set; }
        public string CNP { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public Nullable<int> Varsta { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
